package.json, src/_utils.js, src/sink-gdoc.js, src/sink-gsheet.js, yarn.lock
Closes #4.
Reduction from 101 MB to 11M.
=> Specify scope of google imports

src/sink-gdoc.js, src/sink-gsheet.js
=> Handle output path completely and consistently

.gitignore, README.md, config.example.json, src/sink-fetch.js, src/sink.js
Adds the `fetch` command
N/A
See #8 
1. Clone this repository
2. Run `yarn install`
3. Add a configuration file and authentication file
4. Add a Google Sheet and Document to the configuration
5. Run `node src/sink.js fetch`
6. Run `node src/sink.js doc`
7. Run `node src/sink.js sheet`
No
See #8
=> Add fetch command

src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js
=> Enforce id and output for fetching

src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js
=> Prevent double fetch

src/_utils.js, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js
=> Reorder imports

config.example.json
Changes the example's default authentication file path.
=> Change default auth file path

package.json, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink.js, yarn.lock
=> Bump dependencies

src/sink-fetch.js
=> Add error message when file type is unsupported

src/_utils.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js
=> Abstract common write_file function

package.json, src/sink-csv.js, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js, src/sink.js
=> Add optional chaining to fetch

src/_utils.js, src/sink-csv.js, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js
=> Generalize filled props check

README.md
=> Add AWS IAM instructions

README.md, src/sink-deploy.js
=> Return early if no distribution is specified

src/scripts/deploy.sh
=> Use build variable over dist

README.md, config.example.json, package.json, src/sink-csv.js, src/sink-deploy.js, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js, src/sink-text.js, src/sink.js, yarn.lock
=> Rename `csv` command to `text`

README.md, src/sink-gsheet.js
=> Format different extensions for sheet fetching

README.md, src/sink-deploy.js
=> Run `yarn build` before AWS deployment

src/_utils.js
=> Add meaningful error with missing `auth` property

src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js, src/sink-text.js
=> Catch file not found errors

README.md, src/sink-gsheet.js
=> Support different extensions for fetching all sheets

package.json, src/sink-deploy.js, yarn.lock
=> No empty key

src/_utils.js
=> Fix JS dynamic import for Windows

src/_utils.js
=> Fix exists sync dir check for Windows

.gitignore, src/sink-deploy.js
=> Use posix separators when joining build paths

README.md, src/_utils.js
=> Add support for `.mjs` and `.cjs` configuration extensions

README.md, config.example.json
=> Add instructions for creating a service account

README.md, src/scripts/deploy.sh, src/sink-deploy.js
=> Add `--skip-build` flag on deployment command

README.md, src/sink-deploy.js
=> Make GitHub url optional

README.md, src/scripts/deploy.sh, src/sink-deploy.js
=> Allow for specified deployment branch

src/scripts/deploy.sh, src/sink-deploy.js
=> Remove deploy worktree and branch if not deleted

.gitignore, README.md, example.aws-iam-policy.json, src/sink-deploy.js
=> Find CloudFront distribution if not specified

src/sink-deploy.js
=> Reduce scope of wildcard invalidation

README.md, package.json, src/sink-deploy.js, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js, src/sink-text.js, src/sink.js
=> Patch root key length comparison

src/sink-deploy.js
=> Check for AWS credentials before build

src/sink-deploy.js
=> Exit if deployment fields are missing

README.md, src/_utils.js
=> Get Google authentication config from environment variables

README.md, src/_utils.js, src/scripts/deploy.sh, src/sink-deploy.js
=> Use appropriate package manager

src/sink-deploy.js
=> Exit if key begins or ends with /

src/sink-deploy.js
=> Add flag to answer yes to prompts

README.md, example.sink.config.js, package.json, src/config.js
=> Create typed config function

README.md, example.sink.config.js, src/config.js, src/sink-fetch.js, src/sink-gdoc.js, src/sink-gsheet.js, src/sink-json.js, src/sink-text.js
=> Fall back to top levevl auth

src/config.js
=> Add Google Sheet `extension` type
